"""empty message

Revision ID: 87a3fae76827
Revises: 
Create Date: 2023-07-25 13:11:44.848259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a3fae76827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landmarks', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_landmarks_public_id'), 'landmarks', ['public_id'], unique=False)
    op.add_column('plans', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_public_id'), 'plans', ['public_id'], unique=False)
    op.add_column('plans_to_landmarks', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_to_landmarks_public_id'), 'plans_to_landmarks', ['public_id'], unique=False)
    op.add_column('plans_to_users', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_to_users_public_id'), 'plans_to_users', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_to_users_public_id'), table_name='plans_to_users')
    op.drop_column('plans_to_users', 'public_id')
    op.drop_index(op.f('ix_plans_to_landmarks_public_id'), table_name='plans_to_landmarks')
    op.drop_column('plans_to_landmarks', 'public_id')
    op.drop_index(op.f('ix_plans_public_id'), table_name='plans')
    op.drop_column('plans', 'public_id')
    op.drop_index(op.f('ix_landmarks_public_id'), table_name='landmarks')
    op.drop_column('landmarks', 'public_id')
    # ### end Alembic commands ###
