from dotenv import load_dotenv
import os

load_dotenv()

CELERY_APPLICATION_NAME = os.getenv('CELERY_APPLICATION_NAME')
CELERY_BROKER_PROTOCOL = os.getenv('CELERY_BROKER_PROTOCOL')
CELERY_BROKER_HOST = os.getenv('CELERY_BROKER_HOST')
CELERY_BROKER_PORT = os.getenv('CELERY_BROKER_PORT')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
RABBITMQ_OUTWARD_TOPIC_NAME = os.getenv('RABBITMQ_OUTWARD_TOPIC_NAME')
RABBITMQ_INWARD_TOPIC_NAME = os.getenv('RABBITMQ_INWARD_TOPIC_NAME')
RABBITMQ_TEST_EXCHANGE_NAME= os.getenv('RABBITMQ_TEST_EXCHANGE_NAME')
