import os

from dotenv import load_dotenv

load_dotenv()

LANDMARK_GET_BY_ID_REQUEST_TIMEOUT = os.getenv('LANDMARK_GET_BY_ID_REQUEST_TIMEOUT')
SEARCH_LANDMARK_BY_ID_REQUEST_TIMEOUT = os.getenv('SEARCH_LANDMARK_BY_ID_REQUEST_TIMEOUT')

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
RABBITMQ_USER = os.getenv('RABBITMQ_USER')
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')

RABBITMQ_MAIN_EXCHANGE_NAME = os.getenv('RABBITMQ_MAIN_EXCHANGE_NAME')

RABBITMQ_LANDMARK_GET_BY_ID_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_BY_ID_REQUEST_TOPIC_NAME')
RABBITMQ_LANDMARK_GET_BY_ID_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_BY_ID_RESPONSE_TOPIC_NAME')

RABBITMQ_SEARCH_LANDMARK_BY_RADIUS_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_SEARCH_LANDMARK_BY_RADIUS_REQUEST_TOPIC_NAME')
RABBITMQ_SEARCH_LANDMARK_BY_RADIUS_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_SEARCH_LANDMARK_BY_RADIUS_RESPONSE_TOPIC_NAME')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')

TEST_REDIS_HOST = os.getenv('TEST_REDIS_HOST')
TEST_REDIS_PORT = os.getenv('TEST_REDIS_PORT')
