import os
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv('BASE_URL')
API_KEY = os.getenv('TOMTOM_API_KEY')

RABBITMQ_GET_ALL_LANDMARKS_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_GET_ALL_LANDMARKS_RESPONSE_TOPIC_NAME')
RABBITMQ_GET_ALL_LANDMARKS_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_GET_ALL_LANDMARKS_REQUEST_TOPIC_NAME')
RABBITMQ_MAIN_EXCHANGE_NAME = os.getenv('RABBITMQ_MAIN_EXCHANGE_NAME')