import os
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv('BASE_URL')
API_KEY = os.getenv('TOMTOM_API_KEY')

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
RABBITMQ_USER = os.getenv('RABBITMQ_USER')
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')

RABBITMQ_LANDMARK_GET_BY_ID_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_BY_ID_REQUEST_TOPIC_NAME')
RABBITMQ_LANDMARK_GET_BY_ID_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_BY_ID_RESPONSE_TOPIC_NAME')
RABBITMQ_MAIN_EXCHANGE_NAME = os.getenv('RABBITMQ_MAIN_EXCHANGE_NAME')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')