"""empty message

Revision ID: c0501fb0213c
Revises: 
Create Date: 2023-07-25 17:55:25.250947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0501fb0213c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmarks_description'), 'landmarks', ['description'], unique=False)
    op.create_index(op.f('ix_landmarks_id'), 'landmarks', ['id'], unique=False)
    op.create_index(op.f('ix_landmarks_name'), 'landmarks', ['name'], unique=False)
    op.create_index(op.f('ix_landmarks_public_id'), 'landmarks', ['public_id'], unique=False)
    op.create_index(op.f('ix_landmarks_type'), 'landmarks', ['type'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_completed'), 'plans', ['completed'], unique=False)
    op.create_index(op.f('ix_plans_description'), 'plans', ['description'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_index(op.f('ix_plans_public_id'), 'plans', ['public_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('plans_to_landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=True),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmarks.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_to_landmarks_id'), 'plans_to_landmarks', ['id'], unique=False)
    op.create_table('plans_to_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_to_users_id'), 'plans_to_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_to_users_id'), table_name='plans_to_users')
    op.drop_table('plans_to_users')
    op.drop_index(op.f('ix_plans_to_landmarks_id'), table_name='plans_to_landmarks')
    op.drop_table('plans_to_landmarks')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_plans_public_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_description'), table_name='plans')
    op.drop_index(op.f('ix_plans_completed'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_landmarks_type'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_public_id'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_name'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_id'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_description'), table_name='landmarks')
    op.drop_table('landmarks')
    # ### end Alembic commands ###
