from dotenv import load_dotenv
import os

load_dotenv()

POSTGRES_USERNAME = os.getenv('POSTGRESQL_USERNAME')
POSTGRES_PASSWORD = os.getenv('POSTGRESQL_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRESQL_HOST')
POSTGRES_PORT = os.getenv('POSTGRESQL_PORT')
POSTGRES_DATABASE_NAME = os.getenv('POSTGRESQL_DATABASE_NAME')


POSTGRES_TEST_DATABASE_NAME = os.getenv('POSTGRESQL_TEST_DATABASE_NAME')
POSTGRES_TEST_HOST = os.getenv('POSTGRESQL_TEST_HOST')
POSTGRES_TEST_PORT = os.getenv('POSTGRESQL_TEST_PORT')

LANDMARKS_TABLE_NAME = os.getenv('LANDMARKS_TABLE_NAME')
PLANS_TABLE_NAME = os.getenv('PLANS_TABLE_NAME')
USERS_TABLE_NAME = os.getenv('USERS_TABLE_NAME')
PLANS_TO_LANDMARKS_TABLE_NAME = os.getenv('PLANS_TO_LANDMARKS_TABLE_NAME')
PLANS_TO_USERS_TABLE_NAME = os.getenv('PLANS_TO_USERS_TABLE_NAME')

ALGORITHM = os.getenv('JWT_ALGORITHM')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')
BEARER_TOKEN_URL = os.getenv('BEARER_TOKEN_URL')
ACCESS_TOKEN_EXPIRE_SECONDS = int(os.getenv('ACCESS_TOKEN_EXPIRE_SECONDS'))