"""empty message

Revision ID: 19a9bff096bb
Revises: 87a3fae76827
Create Date: 2023-07-25 13:53:03.047134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a9bff096bb'
down_revision = '87a3fae76827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_to_landmarks_public_id', table_name='plans_to_landmarks')
    op.drop_column('plans_to_landmarks', 'public_id')
    op.drop_index('ix_plans_to_users_public_id', table_name='plans_to_users')
    op.drop_column('plans_to_users', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans_to_users', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_plans_to_users_public_id', 'plans_to_users', ['public_id'], unique=False)
    op.add_column('plans_to_landmarks', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_plans_to_landmarks_public_id', 'plans_to_landmarks', ['public_id'], unique=False)
    # ### end Alembic commands ###
