from dotenv import load_dotenv
import os

load_dotenv()

CELERY_APPLICATION_NAME = os.getenv('CELERY_APPLICATION_NAME')
CELERY_BROKER_PROTOCOL = os.getenv('CELERY_BROKER_PROTOCOL')
CELERY_BROKER_HOST = os.getenv('CELERY_BROKER_HOST')
CELERY_BROKER_PORT = os.getenv('CELERY_BROKER_PORT')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')

RABBITMQ_GET_ALL_LANDMARKS_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_GET_ALL_LANDMARKS_REQUEST_TOPIC_NAME')
RABBITMQ_GET_ALL_LANDMARKS_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_GET_ALL_LANDMARKS_RESPONSE_TOPIC_NAME')
RABBITMQ_MAIN_EXCHANGE_NAME = os.getenv('RABBITMQ_MAIN_EXCHANGE_NAME')
