import os

from dotenv import load_dotenv

load_dotenv()

RABBITMQ_MAIN_EXCHANGE_NAME = os.getenv('RABBITMQ_MAIN_EXCHANGE_NAME')
RABBITMQ_LANDMARK_GET_BY_ID_REQUEST_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_REQUEST_TOPIC_NAME')
RABBITMQ_LANDMARK_GET_BY_ID_RESPONSE_TOPIC_NAME = os.getenv('RABBITMQ_LANDMARK_GET_RESPONSE_TOPIC_NAME')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')